

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: olympics-fe-${{FD_PROJECT_VERSION}}
  namespace: efedorenko
  labels:
    run: olympics-fe
    version: blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: olympics-fe
        version: blue
    spec:
      containers:
      - image: ${{DOCKER_IMAGE}}:${{FD_PROJECT_VERSION}}
        imagePullPolicy: Always
        name: olympics-fe
        ports:
        - containerPort: 80
          protocol: TCP
