

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.deployment.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    run: "{{ .Values.deployment.name }}"
    version: blue
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        run: olympics-fe
        version: blue
    spec:
      containers:
      - image: "{{ .Values.image.name }}"
        imagePullPolicy: Always
        name: olympics-fe
        ports:
        - containerPort: 80
          protocol: TCP
